server:
    port: 8083
    servlet:
      context-path: /ui
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: fooClientIdPassword
      clientSecret: secret
      accessTokenUri: http://localhost:8081/spring-security-oauth-server/oauth/token
      userAuthorizationUri: http://localhost:8081/spring-security-oauth-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8082/spring-security-oauth-resource/users/me
spring:
  thymeleaf:
    cache: false        